### ISSUE TITLE
multi-user support

### ISSUE THREAD

**Issue by ghost** [antoniusmisfit/shoebox-linux#2]
add shadow, gshadow, group, passwd, shells for it

**Comment by antoniusmisfit** [comment]
In build.sh, both /etc/group and /etc/passwd are created, but without any content. So while there's no pre-made user accounts on first boot, the addgroup and adduser commands work. But I do like how you set up a passwordless root on your Janus project, so I may add that feature in. However, adding in /etc/shells only makes sense if you're going to add in shells other than Busybox.

**Comment by ghost** [comment]
if you want use my config files use "old" branch

**Comment by antoniusmisfit** [comment]
BTW, thanks for that pull request. I'm seeing a definite speedup in compilation.
